"""To-Do API — generated by Claude from ai-version/prompt-v1.md. Not hand-written.

Run it with:  uvicorn main_v1:app --reload
"""

from typing import List

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

app = FastAPI(
    title="To-Do API",
    description="A simple in-memory to-do list API built with FastAPI.",
    version="1.0.0",
)


class Task(BaseModel):
    id: int
    title: str
    done: bool = False


class TaskCreate(BaseModel):
    title: str = Field(..., min_length=1, description="What needs to be done")


class TaskUpdate(BaseModel):
    title: str = Field(..., min_length=1)
    done: bool = False


# In-memory storage
tasks: List[Task] = [
    Task(id=1, title="Buy milk", done=False),
    Task(id=2, title="Walk the dog", done=True),
    Task(id=3, title="Finish the report", done=False),
]


def get_task_or_404(task_id: int) -> Task:
    for task in tasks:
        if task.id == task_id:
            return task
    raise HTTPException(status_code=404, detail="Task not found")


@app.get("/tasks", response_model=List[Task])
def list_tasks():
    """Return every task."""
    return tasks


@app.get("/tasks/{task_id}", response_model=Task)
def get_task(task_id: int):
    """Return a single task by id."""
    return get_task_or_404(task_id)


@app.post("/tasks", response_model=Task, status_code=201)
def create_task(payload: TaskCreate):
    """Create a new task."""
    next_id = max((task.id for task in tasks), default=0) + 1
    task = Task(id=next_id, title=payload.title, done=False)
    tasks.append(task)
    return task


@app.put("/tasks/{task_id}", response_model=Task)
def update_task(task_id: int, payload: TaskUpdate):
    """Replace a task's title and done flag."""
    task = get_task_or_404(task_id)
    task.title = payload.title
    task.done = payload.done
    return task


@app.delete("/tasks/{task_id}", status_code=204)
def delete_task(task_id: int):
    """Delete a task."""
    task = get_task_or_404(task_id)
    tasks.remove(task)
