"""To-Do API — generated by Claude from ai-version/prompt-v2.md. Not hand-written.

Run it with:  uvicorn main_v2:app --reload
"""

from typing import Annotated, List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, StringConstraints

app = FastAPI(
    title="Task API",
    description="A simple in-memory to-do list API built with FastAPI.",
    version="1.0",
)

Title = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]


class Task(BaseModel):
    id: int
    title: str
    done: bool = False


class TaskCreate(BaseModel):
    title: Title


class TaskUpdate(BaseModel):
    title: Title
    done: Optional[bool] = None


class ErrorResponse(BaseModel):
    error: str


# In-memory storage
tasks: List[Task] = [
    Task(id=1, title="Buy milk", done=False),
    Task(id=2, title="Walk the dog", done=True),
    Task(id=3, title="Finish the report", done=False),
]


@app.exception_handler(HTTPException)
async def http_exception_handler(request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"error": exc.detail})


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request, exc: RequestValidationError):
    error = exc.errors()[0]
    field = ".".join(str(part) for part in error["loc"][1:]) or "body"
    return JSONResponse(status_code=400, content={"error": f"{field}: {error['msg']}"})


def get_task_or_404(task_id: int) -> Task:
    for task in tasks:
        if task.id == task_id:
            return task
    raise HTTPException(status_code=404, detail=f"Task {task_id} not found")


@app.get("/")
def read_root():
    return {"name": "Task API", "version": "1.0", "endpoints": ["/tasks"]}


@app.get("/health")
def health_check():
    return {"status": "ok"}


@app.get("/tasks", response_model=List[Task])
def list_tasks():
    """Return every task."""
    return tasks


@app.get("/tasks/{task_id}", response_model=Task, responses={404: {"model": ErrorResponse}})
def get_task(task_id: int):
    """Return a single task by id."""
    return get_task_or_404(task_id)


@app.post("/tasks", response_model=Task, status_code=201, responses={400: {"model": ErrorResponse}})
def create_task(payload: TaskCreate):
    """Create a new task."""
    next_id = max((task.id for task in tasks), default=0) + 1
    task = Task(id=next_id, title=payload.title, done=False)
    tasks.append(task)
    return task


@app.put(
    "/tasks/{task_id}",
    response_model=Task,
    responses={400: {"model": ErrorResponse}, 404: {"model": ErrorResponse}},
)
def update_task(task_id: int, payload: TaskUpdate):
    """Update a task. An absent `done` leaves the existing value alone."""
    task = get_task_or_404(task_id)
    task.title = payload.title
    if payload.done is not None:
        task.done = payload.done
    return task


@app.delete("/tasks/{task_id}", status_code=204, responses={404: {"model": ErrorResponse}})
def delete_task(task_id: int):
    """Delete a task."""
    tasks.remove(get_task_or_404(task_id))
